### ISSUE TITLE
libxml2 does not cross build correctly with a minimal sysroot, can use zlib subproject fallback

### ISSUE THREAD

**Issue by dabrain34** [mesonbuild/libxml2#10]
Here is [libxml2-2.9.7-6-wrap.zip](https://github.com/mesonbuild/libxml2/files/4170571/libxml2-2.9.7-6-wrap.zip)
 for it

**Comment by legeana** [comment]
Sorry, I don't understand the request. Could you please rephrase and provide more details?

**Comment by dabrain34** [comment]
oups, yes. I'm cross building a project (gst-build) for an arm target with no zlib in my sysroot. Seen that this project (gst-build) includes both zlib and libxml2, I added in the libxml2 patch package (meson.build) the fallback to zlib. Could you update the patch package or can I do it ?

**Comment by legeana** [comment]
Pull requests are welcome. I didn't see a patch, only a zip file from you. It's very hard to see what you have actually changed without a diff.
I am still confused what you are trying to do so maybe pull request will be helpful.
Thank you!

**Comment by dabrain34** [comment]
I would have prefered to do a PR but I did not know where and how seen that we rely on a package.
Can you lead me to the right repo to add in libxml2/meson.build the fallback of zlib ?

**Comment by legeana** [comment]
Apologies, I don't understand what you are asking.

**Comment by tp-m** [comment]
Perhaps the confusion stems from the fact that in the `master` branch there are no `meson.build` etc. files.

So I guess a PR should be done against the [2.9.7 version branch](https://github.com/mesonbuild/libxml2/tree/2.9.7) then?

**Comment by dabrain34** [comment]
```
- zlib_dep = dependency('zlib', required: false)
+ zlib_dep = dependency('zlib', required: false, fallback: ['zlib', 'zlib_dep'])
```

I'd like to change this line in libxml2's meson.build :)

**Comment by dabrain34** [comment]
indeed ! thx @tp-m :+1:

**Comment by legeana** [comment]
So basically @dabrain34 what you need to do is:
1. fork a repo
2. switch to a branch of the version you would like to patch
3. make a commit and push it to your own copy of the repo (your fork)
4. submit a pull request to the repo here
